server:
  port: ${SERVER_PORT:5004}
  servlet:
    context-path: ${CONTEXT_PATH:/post}

spring:
  application:
    name: ${APP_NAME:post-service}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://admintam:21maichitam07@databaseparking2.2bt5tn6.mongodb.net/clone-fb-post-service?appName=DatabaseParking2}

app:
  services:
    profile:
      url: ${PROFILE_SERVICE_URL:http://localhost:5002/profile}

logging:
  level:
    root: ${LOGGING_LEVEL:INFO}
    "[com.tam.post]": ${LOGGING_LEVEL:INFO}